name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    if: true
    runs-on: ubuntu-latest

    steps:
      # Vérifie le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Se connecter au GitHub Container Registry (ghcr.io)
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      # Construire et pousser l'image Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/yamakajump/selenium-emarge:latest
